#!/bin/bash

function main {

	if [ -z "$1" ]
	then
		clear
		
		menu
		
		read input # prompt
		
		if [ $input -eq 1 ]
		then 
			# SERVER
			server
		elif [ $input -eq 2 ]
		then 
			# CLIENT
			client
		else
			echo "###ERROR###"
			sleep 1
			main
		fi
	elif [ ! -z "$2" ]
	then
		if [ "$1" == "server" ]
		then
			server $2
		elif [ "$1" == "client" ]
		then
			client $2
		else
			echo "Usage: netget {server | client} FILENAME"
		fi
	else 
		echo "Usage: netget {server | client} FILENAME"
	fi

}

function menu {
	
	echo "Welcome to netget"
	echo "What can I do for you?"
	echo "	-[1] Share a file."
	echo "	-[2] Take a file."
	echo -n "> "
}

function server() {
	if [ ! -z "$1" ]
	then
		echo $1
	else
		echo "From the menu"
	fi
}

function client()  {
	if [ ! -z "$1" ]
	then
		echo $1
	else
		echo "From the menu"
	fi
}

function getFileName {
	echo ""
}

main $1 $2
