#!/bin/bash

function main {

	if [-z "$1"];then
		clear
		
		menu
		
		read input # prompt
		
		if [$input == '1'];then # SERVER
			server
		elif [$input == '2'];then # CLIENT
			client
		else
			echo "###ERROR###"
			sleep 1
			main
		fi
	else
		if [$1 == 'server'];then
			
		elif [$1 == 'client'];then

		else
			echo "Usage: netget {server | client} FILENAME"
		fi
	fi

}

function menu {
	
	echo "Welcome to netget"
	echo "What can I do for you?"
	echo "	-[1] Share a file."
	echo "	-[2] Take a file."
	echo "> "
}

function server {

}

function client {

}

function getFileName {

}

main
