#!/bin/bash
# License : GPL v3.0
# Created by Saman Ebrahimnezhad .

function main {

	if [ -z "$1" ]
	then
		clear
		
		menu
		
		read input # prompt
		
		if [ $input -eq 1 ]
		then 
			# SERVER
			server
		elif [ $input -eq 2 ]
		then 
			# CLIENT
			client
		else
			echo "###ERROR###"
			sleep 1
			main
		fi
	elif [ ! -z "$2" ]
	then
		if [ "$1" == "server" ]
		then
			server $2
		elif [ "$1" == "client" ]
		then
			if [ ! -z "$3" ]
			then
				client $2 $3
			else
				usage
			fi
		else
			usage
		fi
	else 
		usage
	fi

}

function menu {
	echo "Welcome to netget"
	echo "What can I do for you?"
	echo -e "	-[\033[1;34m1\033[0m] Share a file."
	echo -e "	-[\033[1;34m2\033[0m] Take a file."
	echo -ne "\033[1;34m>\033[0m "
}

function server() {
	if [ ! -z "$1" ]
	then
		/usr/share/netget/server.py $1
	else
		echo -n "Enter the full path of your file> "
		read fileName
		/usr/share/netget/server.py $fileName
	fi
}

function client()  {
	if [ ! -z "$1" ]
	then
		/usr/share/netget/client.py $1 $2	
	else
		echo -n "Enter the server ip> "
		read serverIp
		echo -n "Enter a name for downloaded file> "
		read fileName
		/usr/share/netget/client.py $serverIp $fileName
	fi
}

function usage {
	echo "Usage: netget {server | client} [IP_ADDRESS(for client)] FILENAME"
}

main $1 $2 $3
